### ISSUE TITLE
Add link to this project as issue in original project

### ISSUE THREAD

**Issue by WilczynskiT** [jacobwhall/marktext#12]
@jacobwhall Please add issue in marktext/marktext with information that here is the actual project. 

A lot of people contact with me, and then I am sending them link to this repository.

I propose title like: NEW REPO / REACTIVATION

**Comment by jacobwhall** [comment]
Hey @WilczynskiT, thanks for your issue.

To be honest, I don't feel comfortable adding an issue to the upstream repository advertising this fork. I think I've been daring enough to post links to this fork on issues regarding the future of MarkText. The interest I've received so far has been awesome, with a few people already offering tangible help with development work.

It's a bit frustrating to think that someone looking for an up-to-date MarkText might not discover our project. Especially once we start releasing multiplatform builds (#2), I'll be hoping to reach a larger audience. Given the amount of engagement in the upstream repository today, it is clear that there is demand for the work we're doing here. Perhaps there are other ways for us to advertise? If we have an active project with a nice-looking website for example, it seems likely that this project will blossom.

I wonder if there are other examples of forked repositories we could investigate to see if there are best practices for handling this type of situation. My goal is that if one of the owners of the upstream repository come across this project, they won't feel like we poached any interest from their work in an aggressive way.

**Comment by WilczynskiT** [comment]
Hey @jacobwhall 

I understand your concerns regarding the project's licensing and the author's intentions. The project is under the MIT license, indicating that the author is likely aware of its implications. By contributing to the project and avoiding the loss of human resources involved, we can help continue their work.

If the author returns, we can collaborate and create pull request to hand over control of the repository. Additionally, I can assist by advertising your repository in the original markdown issue, with your permission.

Alternatively, I can take full responsibility by cloning the project to my own repository and granting you access as an organization member. This way, we can ensure continued development and collaboration while full responsibility will be on me

**Comment by jacobwhall** [comment]
@WilczynskiT

> The project is under the MIT license, indicating that the author is likely aware of its implications.

Yes, this is true. My concern revolves around respecting the sense of ownership prior maintainers surely have over this project. I want to tread lightly in their own issue tracker. Some time has passed since they last were merging PRs and responding to issues, but not so much time that they couldn't start back up again.

> If the author returns, we can collaborate and create pull request to hand over control of the repository.

The authors may or may not like the direction we've taken MarkText. This fork has already merged tens of features, we are reworking the build system, and are discussing other major renovations of the project. I know the README currently says I'd be happy to hand it back over to the original authors (and that's true), but our project identity is quickly diverging from theirs.

> Alternatively, I can take full responsibility by cloning the project to my own repository and granting you access as an organization member.

Thanks for your offer, and forgive me for wanting to hold on to this repository for now. I've done the work to merge a bunch of features into the project, and I've already received positive feedback about this fork. I will happily discuss any ideas folks have for the project, and accept PRs that further its reliability and feature set. I'm open to adding more collaborators to the repository itself as they show continued interest in contributing.

I think your idea about creating a new organization for this fork is a good one, but I'd like to wait a bit before doing so. I think the benefits of creating an organization become more apparent once you have more than a couple active contributors, and doing so would require serious discussion about our branding and general identity as a project. I'd like to discuss how our name, logo, mission might change in separate issues, for example.

**Comment by WilczynskiT** [comment]
Thanks for the response. I think that issue could be closed. I see that you know what you’re doing. Let’s give it time to grow. 😉
